# Generated by Django 5.1.1 on 2025-02-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='santori',
            name='aruaru',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='santori',
            name='daijobu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='santori',
            name='ganba',
            field=models.IntegerField(default=0),
        ),
    ]
