# Generated by Django 5.1.1 on 2024-12-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconfig',
            name='memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
