# Generated by Django 5.1.1 on 2025-01-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='time',
            new_name='time1',
        ),
        migrations.AddField(
            model_name='date',
            name='time2',
            field=models.TimeField(max_length=200, null=True),
        ),
    ]
