# Generated by Django 5.1.1 on 2024-12-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventconfig_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventconfig',
            name='memo',
            field=models.CharField(max_length=200),
        ),
    ]
