# Generated by Django 5.1.1 on 2024-11-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventconfig_delete_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventconfig',
            old_name='question_text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='eventconfig',
            name='pub_date',
        ),
    ]
