# Generated by Django 5.1.1 on 2025-01-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_createdate_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createddate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(max_length=200),
        ),
    ]
