# Generated by Django 5.1.1 on 2025-01-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_createddate_created_at_alter_date_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='date',
            new_name='day',
        ),
    ]
