# Generated by Django 5.1.1 on 2025-01-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_date_date_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.CharField(max_length=200),
        ),
    ]
