# Generated by Django 5.1.1 on 2025-01-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_date_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventconfig',
            name='memo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
