# Generated by Django 5.1.1 on 2025-01-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_eventconfig_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventconfig',
            name='memo',
            field=models.CharField(max_length=200),
        ),
    ]
